---
# ROLE: hydra-stack
# roles/hydra-stack/install/tasks/fedora.yml
#
- name: download fedora
  become: yes
  get_url:
    url: "{{ fedora_url }}"
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    dest: "{{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war"
    timeout: 100
  tags:
    - fcrepo4

- name: make fedora data dir
  file:
    owner: "{{ tomcat_name }}"
    group:  "{{ tomcat_name  }}"
    state: directory
    path: "{{ fedora_data_directory_path  }}"
  become: yes
  tags:
    - fcrepo4

- name: check fedora.war
  become: yes
  stat:
    path: "{{ tomcat_path }}/webapps/fedora.war"
  register: fedora_war


- name: copy over fedora.war
  become: yes
  shell: >
    cp {{ install_path }}/fcrepo-webapp-{{ fedora_version }}.war {{ tomcat_path }}/webapps/fedora.war
  notify: restart tomcat
  when: fedora_war.stat.exists == False
  tags:
    - fcrepo4

- name: Determine java home
  shell: >
    readlink -f /usr/bin/javac | sed 's:/bin/javac::'
  register: java_home_registered
  changed_when: False
  tags:
    - fcrepo4

- name: Set java_home variable
  set_fact:
    java_home: "{{ java_home_registered.stdout }}"
  tags:
    - fcrepo4

- name: create tomcat config and java options
  become: yes
  template:
    src: tomcat.j2
    dest: /etc/default/{{ tomcat_name }}
    backup: yes
  notify: restart tomcat
  tags:
    - fcrepo4

